name: dartx
version: 0.0.1
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Dartx it is designed to run standalone command-line scripts at any place without requirements to pre-install these scripts. It can be used for writing a small batch files in Dart language.
homepage: https://github.com/mezoni/dartx
dev_dependencies:
  path: any
